### ISSUE TITLE
Unable to apply attachment to more than 50-64 products

### ISSUE THREAD

**Issue by Tjitse-E** [mageprince/magento2-productAttachment#10]
Hi,

I'm using Magento 2.1.10 and PHP7. I've got the following problem with mageprince/magento2-productAttachment; i'm unable to add more products to one of the attachments using the admin panel.

I've made a screen recording of the issue: http://sendvid.com/87yu1e0g

Notice that at first, we've got 64 products attached to the attachment. After adding 3 products this number stays the same.

I've looked into the source code of the module but I didn't find any obvious issues there. Does anyone experience the same problem?

**Comment by unicoder88** [comment]
Hi @Tjitse-E ,
I think the problem is that assigned products are saved in one column with fixed length 255 https://prnt.sc/i809ot
Easy solution - change column type to text.

**Comment by Tjitse-E** [comment]
@unicoder88 , thanks for your solution. I've just tested this on staging and it works.

**Comment by mageprince** [comment]
The issue has been fixed. Please check commit [b8d80f0](https://github.com/mageprince/magento2-productAttachment/commit/b8d80f0f7ced32fb1f73c18d987eb9d56166e11d) by @Tjitse-E
