### ISSUE TITLE
Product Attachment/Manage Attachments not working

### ISSUE THREAD

**Issue by Karsten8886** [mageprince/magento2-productAttachment#11]
I installed the Product Attachment in a Magento ver. 2.1.7 store. Now i see the extension in the magento backend.
But when ich click on "Manage Attachments" i come to the admin dashboard. It is not possible to add Attachments.
Could you please give me an answer or any help to find the problem?

**Comment by mageprince** [comment]
@Karsten8886 
Please run following command and try:
`php bin/magento setup:di:compile`

**Comment by Karsten8886** [comment]
Thanks for the Info, but no it doesen't change

**Comment by Karsten8886** [comment]
Hello, now i removed the extension an make a new install. But it doesen't change. It is nor possible to add Attachments. 
I copied the Extension in app/code/prince/module-productattachment

Then i use this commands:
php_cli bin/magento setup:upgrade
php_cli bin/magento setup:static-content:deploy
php_cli bin/magento cache:flush
php bin/magento setup:di:compile

But it is nor working

**Comment by mageprince** [comment]
@Karsten8886 , thank you for your report.
I am not able to reproduce this issue by following the steps you provided.
We tested the issue on, 2.2.2, 2.2.1, 2.2.0, 2.1.9
