### ISSUE TITLE
Base table or view not found

### ISSUE THREAD

**Issue by jeffmalterre** [mageprince/magento2-productAttachment#12]
Just installed the module.

In the backend, Product Attachment -> Manage Attachments

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cfs.prince_productattach' doesn't exist, query was: SELECT COUNT(*) FROM `prince_productattach` AS `main_table`

**Comment by mageprince** [comment]
**@jeffmalterre,** Thank you for posting issue. But I have not found any issue with default Magento 2.2.x setup. Please provide screenshot or video to identify the issue.

Please check your database that `prince_productattach` table generated or not. If not generated then remove `Prince_Productattach` module entry from `setup_module` table and run php bin/magento setup:upgrade command to regenerate table.

**Comment by jeffmalterre** [comment]
php bin/magento setup:upgrade is not generating the table

**Comment by jeffmalterre** [comment]
That worked, thanks!
