### ISSUE TITLE
Add the module to packagist

### ISSUE THREAD

**Issue by Spaggel** [mageprince/magento2-productAttachment#15]
Hi,

Thanks for making this module free & open source.

I was wondering if you could add this module to packagist.org so installing using composer will be easier. Feel free to ask for my support if needed.

Thanks for your time!

**Comment by mageprince** [comment]
@Spaggel Thanks for using module. 
I will update my composer.json. After you can use composer to download this module from Git repo.
In another way this extension is already on Magento Marketplace you can use composer with Magento repo: https://marketplace.magento.com/prince-module-productattachment.html

**Comment by Spaggel** [comment]
Thank you!
