### ISSUE TITLE
Unable to upload load attachments

### ISSUE THREAD

**Issue by manikumaran1978** [mageprince/magento2-productAttachment#16]
I was using this module and was working fine in magento community 2.2.1
After upgrading to magento 2.2.2 the attachments does not upload.

**Comment by manikumaran1978** [comment]
I get this error
Loading failed for the <script> with source “...../static/adminhtml/Magento/backend/en_US/jquery/fileUploader/bootstrap.min.js”.

**Comment by mageprince** [comment]
Hi @manikumaran1978. Thank you for your report.
The issue has been fixed. Please check commit: [622de07](https://github.com/mageprince/magento2-productAttachment/commit/622de0767dfd499a3ba8a4021f25df20779bec7c)

**Comment by manikumaran1978** [comment]
Thank you the issue is solved.
