### ISSUE TITLE
There is a missing interface

### ISSUE THREAD

**Issue by siper92** [mageprince/magento2-productAttachment#17]
Magento 2.2  DI compiles gives an error because there is a missing generator

This is the error message                                                                               
` 
[ReflectionException]                                                                     
  Class Prince\Productattach\Api\Data\FileiconSearchResultsInterfaceFactory does not exist  
                                                             
  [ReflectionException]                                                                     
  Class Prince\Productattach\Api\Data\FileiconSearchResultsInterfaceFactory does not exist  
                                                                                                       
  [RuntimeException]                                                                                               
  Source class "\Prince\Productattach\Api\Data\FileiconSearchResultsInterface" for "Prince\Productattach\Api\Data  
  \FileiconSearchResultsInterfaceFactory" generation does not exist. 
`

**Comment by mageprince** [comment]
Hi @siper92  Thank you for your report.
The issue has been fixed. Please check commit: [a1403c7](https://github.com/mageprince/magento2-productAttachment/commit/a1403c7555d36fc4db93bd20d54fd018b398493d)
