### ISSUE TITLE
Reinstallation issues

### ISSUE THREAD

**Issue by jeffmalterre** [mageprince/magento2-productAttachment#18]
I tested this extension a few months ago and ran into a few problems so I removed it.  I just now tried reinstalling it and it works on a fresh site.  However, when I try to install it again on the site I uninstalled it from, I get a few problems:

1.  Tables are not recreated in the database - I had to manually create them
2.  I set an attachment to a product.  When I go to view that product I get an error:

1 exception(s):
Exception #0 (Exception): Warning: get_headers(): php_network_getaddresses: getaddrinfo failed: Name or service not known in app/code/Prince/Productattach/Block/Attachment.php on line 235

However, like I said this extension works perfectly on a fresh site.  I'm just having problems on the site that I used to have it installed on.

Thanks,
Jeff

**Comment by jeffmalterre** [comment]
Nvm fixed (by fixed i mean i disabled show attachment size)

**Comment by mageprince** [comment]
Hi @jeffmalterre  Thank you for your report.
I think this is php version issue. Becuase as you can see function `remoteFileSize()` at `magento2-productAttachment/Block/Attachment.php` we used `get_headers()` function to get file size by url.

We will update this code to get size by file. Meanwhile you can set Admin->Stores->Configuration->Mageprince->ProductAttachment->Show Attachment Size to NO

**Comment by mageprince** [comment]
Hi @jeffmalterre Thank you for your report.
The issue has been fixed. Please check commit: [a27f0ec](https://github.com/mageprince/magento2-productAttachment/commit/a27f0ec3392a56ea860ba76ce033a6125204e156)
