### ISSUE TITLE
Can't add more than 51 products

### ISSUE THREAD

**Issue by jeffmalterre** [mageprince/magento2-productAttachment#19]
I was adding products to an attachment and I realized that when I went to add more, it would say that it got added but it doesn't.  I tried removing a product and adding a different one, that worked - bringing it back to 51 products.  But I'm still not able to add more.

I also tried with another attachment and I'm experiencing the same thing.

Using latest files as of 3/21/18

Thanks,
Jeff

**Comment by mageprince** [comment]
Hi @jeffmalterre Thank you for your report.
The issue has been fixed. Please check commit: [67ce12c](https://github.com/mageprince/magento2-productAttachment/commit/67ce12c81e4d3ea3c5728e9a5071d68529a35d47)
