### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by gewaechshaus** [mageprince/magento2-productAttachment#2]
Hi Prince108,

we noticed some issues with compilation on MCE2.1.7

        Errors during compilation:
        Prince\Productattach\Block\Attachment
        Incorrect dependency in class Prince\Productattach\Block\Attachment in 
        /var/www/html/app/code/Prince/Productattach/Block/Attachment.php
        \Magento\Framework\App\Config\ScopeConfigInterface already exists in context object

Regards
Jan

**Comment by mageprince** [comment]
@gewaechshaus Thanks for reporting an issue. This issue has been solved. You need to replace this two files from latest repository code.
```
1) app/code/Prince/Productattach/Helper/Data.php
2) app/code/Prince/Productattach/Block/Attachment.php
```

Now run _php bin/magento setup:di:compile_
and flush cache
