### ISSUE TITLE
Show attachments for all products?

### ISSUE THREAD

**Issue by pixelpath** [mageprince/magento2-productAttachment#20]
Is there a way to generate a page or block that lists all product attachments dynamically? If possible, I'd like to make a page called Support Files that lists all attachments for our products in one place. 

Thanks for this excellent module!

**Comment by mageprince** [comment]
@pixelpath Thank you for your suggestion.
We will add this functionality in next version of the module.

Meanwhile you can use `getCollection()` function of `Prince\Productattach\Model\ResourceModel\Productattach\Collection` class to get all attachments of all products.

Check this file for more details: https://github.com/mageprince/magento2-productAttachment/blob/master/Block/Attachment.php

**Comment by pixelpath** [comment]
Thank you! Thats exactly what I was looking for. Here is my phtml file if anyone is interested:
```
<?php 
	$blockObj = $block->getLayout()->createBlock('Prince\Productattach\Block\Attachment');
	$attachments = $blockObj->getCollection();
	$isSize = $blockObj->getConfig('productattach/general/attachmentsize');
?>

<ul class="product-attachments">
	<?php foreach ($attachments as $attachment) : ?>
		<?php if ($attachment->getActive()) : ?>
			<li class="attachment">
				<a href="<?php /* @noEscape */ echo $blockObj->getAttachmentUrl($attachment->getFile()); ?>" target="_blank">
					<div class="attachment-icon" style="float: left; padding-right: 10px;">
						<img src="<?php /* @noEscape */ echo $blockObj->getFileIcon($attachment->getFileExt()) ?>" style="width: 20px"/>
					</div>
		    		<?php echo $attachment->getName() ?>
				</a>
				<?php if ($isSize) : ?>
					<?php $size = '(Size: '.$blockObj->getFileSize($attachment->getFile()).')' ?>
					<?php /* @noEscape */ echo __($size); ?>
				<?php endif; ?>
			</li>
		<?php endif; ?>
	<?php endforeach; ?>
</ul>
```
