### ISSUE TITLE
file Prince\Productattach\Block\Adminhtml\Productattach\Renderer\Store

### ISSUE THREAD

**Issue by rendybustari** [mageprince/magento2-productAttachment#22]
Hi @mageprince ,how i can find file Prince\Productattach\Block\Adminhtml\Productattach\Renderer\Store ?

because in folder Prince\Productattach\Block\Adminhtml\Productattach\Renderer\ just have 2 files, FileIcon.php and FileIconAdmin.php

thank you

**Comment by mageprince** [comment]
Hi @rendybustari , Thank you posting issue.
I have not used `Grid.php` for listing attachments in admin. I have used UI grid which is at `/var/www/html/mage222/app/code/Prince/Productattach/view/adminhtml/ui_component/productattach_grid_index.xml` Here you can find store renderer class which is `Prince\Productattach\Ui\Component\Listing\Column\Store`
Grid.php is not used anywhere now. Will remove in next version of the module.
