### ISSUE TITLE
Suggestion: If possible, Also provide support for rest Api 

### ISSUE THREAD

**Issue by ankit-sf** [mageprince/magento2-productAttachment#23]
If possible, Also provide support for rest Api

**Comment by mageprince** [comment]
@ankit-sf Thank you for your suggestion. I will add in next version of this module.

**Comment by magento2dev** [comment]
It will be the perfect module with rest API support :)

**Comment by mageprince** [comment]
Hi, @ankit-sf and @anthony-jullien Thank you for your suggestion.
I will add rest API support in the next version of this module.

**Comment by magento2dev** [comment]
Hi,
Great news ! :)
Thanks for this great free module

**Comment by magento2dev** [comment]
Hello @mageprince,
Sorry to disturb you again but do you have any idea when the rest API will be available ?

Thanks !

**Comment by magento2dev** [comment]
Thanks @mageprince ! I hope to get it soon for my project, it will save me a lot of time :)

**Comment by mageprince** [comment]
Hi @magento2dev @ankit-sf Rest API for add, update and delete attachments are added by @giuseppemorelli. Please check related commits: [2231c5e](https://github.com/mageprince/magento2-productAttachment/pull/37/commits/63f947e4ed55269b0eb06122f3c8df1ea2231c5e)
