### ISSUE TITLE
Product Attachments not visible for guests.

### ISSUE THREAD

**Issue by TobiasLufinity** [mageprince/magento2-productAttachment#27]
If you have a user that is not logged in and Customer Group is set to "NOT LOGGED IN" on a file the Product Attachment tab doesn't show. 

![image](https://user-images.githubusercontent.com/32361984/39912475-21392934-54ff-11e8-9916-c6fc9f3dc3e7.png)

![image](https://user-images.githubusercontent.com/32361984/39912490-2fb3f7d2-54ff-11e8-8897-dbb9e5e43279.png)

If you pick General with the tab shows again even if the customer isn't logged in. 

![image](https://user-images.githubusercontent.com/32361984/39913179-3e4b1076-5501-11e8-8add-35305dfae467.png)

![image](https://user-images.githubusercontent.com/32361984/39912576-7530ba70-54ff-11e8-9e3b-725de5e5fd77.png)

**Comment by mageprince** [comment]
Hi @AndreKlang And @TobiasCodeNull 
Thank you for your contributions.
