### ISSUE TITLE
Cache on product-page is killed

### ISSUE THREAD

**Issue by AndreKlang** [mageprince/magento2-productAttachment#32]
You are using ```cacheable="false"``` on two blocks on the product page. That is **EXTREMELY** bad practice since it renders the page uncacheable in FPC.

See: [docs](https://devdocs.magento.com/guides/v2.2/extension-dev-guide/cache/page-caching.html#cache-over-cacheable)

**Comment by mageprince** [comment]
Hi @AndreKlang 
Yes, you are right. Also, Magento marketplace not approved an extension if we use cacheable="false" in the layout.

Thank you for your suggestion. I removed cacheable="false" from the layout.
Check commit: [5172fd43](5172fd4360131205e748affba001675dc3a0804e)
