### ISSUE TITLE
Iam using Magento2.1.7 after installation iam getting error

### ISSUE THREAD

**Issue by chalapathipakkela** [mageprince/magento2-productAttachment#35]
Hi

Iam using Magento2.1.7 after installation iam tring to add New Attachment
from that time iam  getting error like this

There has been an error processing your request
Notice: Array to string conversion in /home/admin/public_html/vendor/magento/framework/App/Config.php on line 84
and url is http://localhost/admin/productattach/index/new/key/5dd8b402205028e0d833f210dd8d0e34a4f027fa8fba415630d708d1a21b28d0/

Please help me out on this 
Thanks in advance

**Comment by mageprince** [comment]
Hi @chalapathipakkela Thank you for your report. This module is tested from Magento 2.1.x to Magento 2.2.4. Please try to reproduce this issue on fresh Magento setup.
