### ISSUE TITLE
Frontend Layout

### ISSUE THREAD

**Issue by iffatishi** [mageprince/magento2-productAttachment#36]
Hi, installed the extension from marketplace. The frontend layout got distorted as it stopped reading the CSS after installing the extension.

**Comment by mageprince** [comment]
@iffatishi thank you for your report.
I was not able to reproduce this issue in default Magento setup. Please try to reproduce this issue on a clean installation or latest release. Also please check this installation Guide: https://devdocs.magento.com/guides/v2.2/comp-mgr/install-extensions.html
