### ISSUE TITLE
Getting logged out

### ISSUE THREAD

**Issue by fdfx** [mageprince/magento2-productAttachment#38]
After installing this extension and clearing the cache, when Itry to save a new file attachment I get forcibly logged out. It looks like a great extension but obviously this issue will prevent me from using it. Do you have any idea why this might be happening?

I'm using Magento 2.2.5 and I'm logged in as the original Administrator.

**Comment by mageprince** [comment]
@fdfx Thank you for your report. 
I am not able to reproduce this issue in fresh Magento 2.2.5 setup. Please check it with the fresh installation of Magento.
