### ISSUE TITLE
Not registered handle productattach_grid_index_data_source

### ISSUE THREAD

**Issue by nagarajuk12** [mageprince/magento2-productAttachment#39]
Hi Prince,

Thank you for providing useful extension which you have made in magento2.
but we are facing two issues they are 

1) in the admin end displaying an error like "**Not registered handle productattach_grid_index_data_source**"  after installation has been successfully.

https://prnt.sc/kvdc12

I am using Magento 2 version:- Magento 2.2.5 CE
Please advise. 
Thanks

**Comment by mageprince** [comment]
@KnagarajuK Thank you for your report.
I am not able to repoduce this issue in fresh Magento 2.2.5 setup.

Please check line [L14](https://github.com/mageprince/magento2-productAttachment/blob/master/etc/di.xml#L14) I already register handle `productattach_grid_index_data_source` in collection `Magento\Framework\View\Element\UiComponent\DataProvider\CollectionFactory`

Please check again after running following commands
php bin/magento setup:upgrade
php bin/magento cache:flush
rm -r var/ generated/
