### ISSUE TITLE
Multiple PDF's show on the wrong products.

### ISSUE THREAD

**Issue by mosaiceye** [mageprince/magento2-productAttachment#4]
Hello-

Just thought I'd give you a heads up, that I've been using your Magento 2 extension and I noticed that in Prince/Productattach/Block/Attachment.php on line 93:

`$collection->getSelect()->where("products LIKE '%".$productId."%' COLLATE utf8_bin");`

I had 1 PDF uploaded and associated with a product id of 5, yet on the frontend it shows up on both product 5 and 54. This query works, minus the fact that I only want the PDF to show up on 5 and not 54. Any chance this could be resolved?

Nice extension though, very helpful. I'm still looking into a fix for this, but thought you could solve it faster. Let me know your thoughts,

Thanks,
Tony

**Comment by mageprince** [comment]
@mosaiceye Hi, 

Thanks for submitting an important issue. I will get back after checking this issue.

Thank You,
Prince Patel

**Comment by mosaiceye** [comment]
Thanks Prince, let me know what you find out. -Tony

**Comment by mageprince** [comment]
@mosaiceye Hi,

No issue found in assigning product in the attachment. I tested it after applying in product ID 2, The attachment only shows in product id 2, not in 20,21 or any other products. Make sure you have only selected particular product.

Thank You,
Prince Patel

**Comment by mosaiceye** [comment]
I'm certain it was only in that one. Which version of Magento are you
testing on?

Tony

**Comment by mageprince** [comment]
@mosaiceye Hi,

I tested this module in all 2.1.x versions.

**Comment by mosaiceye** [comment]
Hey Prince-

Not sure how it worked for you and not me. I'm on Mag 2.1.7. However, I added this line:
$collection->getSelect()->where("products REGEXP '[[:<:]]" . $productId . "[[:>:]]'");

And it worked for me. Thanks, Tony

**Comment by mageprince** [comment]
@mosaiceye Hi, I got another same issue here: 
https://github.com/prince108/magento2-productAttachment/issues/5
After checking deeply on this issue. I found that error exists there and now it's solved. plz change code as you suggest at line 93 to `$collection->getSelect()->where("products REGEXP '[[:<:]]".$productId."[[:>:]]'");`
thanks for your suggestion.

**Comment by mosaiceye** [comment]
No problem happy to help!
