### ISSUE TITLE
Use attachment block on other cms content pages

### ISSUE THREAD

**Issue by oliverp44** [mageprince/magento2-productAttachment#40]
Is there a way to display the attachment block on other pages ?

**Comment by mageprince** [comment]
@oliverp44 I will add functionality like showing all product's attachments in one page in the next version of this module.

**Comment by dbartelmus** [comment]
Hello, I can see that you've updated module 5 days ago. Is this feature available?

**Comment by dbartelmus** [comment]
In general I'm using https://www.magesolution.com/product-tabs-for-magento-2.html and this module doesn't consider any other extension despite its own, so whenever Protabs is enabled I don't see attachments.

I think shortcode like widget use in html will do the job

**Comment by gotgelf** [comment]
Is it possible to update product via rest api and provide attachments ids?

**Comment by mageprince** [comment]
> Hello, I can see that you've updated module 5 days ago. Is this feature available?

Hi @dbartelmus 
This feature is available in the next version(1.2.0) of the module which is currently on QA review on Magento Marketplace. I will update you once this version approved on Magento Marketplace.

**Comment by mageprince** [comment]
> In general I'm using https://www.magesolution.com/product-tabs-for-magento-2.html and this module doesn't consider any other extension despite its own, so whenever Protabs is enabled I don't see attachments.
> 
> I think shortcode like widget use in html will do the job

Hi @dbartelmus 
We added the attachment tab in `product.info.details` block. Please check third-party module code and add `productattach.tab` block to show attachment tab.

**Comment by mageprince** [comment]
> Is it possible to update product via rest api and provide attachments ids?

Hi @gotgelf 
No, It is not possible. You can use `UpdateInsertAttachment` API to add a new attachment with products assignments.

**Comment by mageprince** [comment]
> Is there a way to display the attachment block on other pages ?

@oliverp44 @dbartelmus This functionality now available with latest version of this module. Please download latest version of this module: [Download](https://marketplace.magento.com/prince-module-productattachment.html)

**Comment by mageprince** [comment]
> Is it possible to update product via rest api and provide attachments ids?

@oliverp44 @dbartelmus @gotgelf The latest version of the module provides API support. You can add, update, get and delete attachments by rest API. Now you can also get, assign/remove attachments from the product API.

Please download the latest version of the module from the Magento Marketplace. [Download](https://marketplace.magento.com/prince-module-productattachment.html).
