### ISSUE TITLE
request does not match route

### ISSUE THREAD

**Issue by Daniel304** [mageprince/magento2-productAttachment#41]
I have installed everything like it supposed to with composer.
I enabled the module through the admin and i am able to upload pdf's and attach them to a product. 
In an effort to automate thing i tried using the rest api as my shops inventory runs entirely on the api
But I get the error request doe snot match route, i use this route
[myshopurl]/rest/V1/productattach/addupdate
[myshopurl]/swagger
doesn't show the product attachment..
Please help

**Comment by mageprince** [comment]
@Daniel304 Thank you for your report.
The latest API code was not updated on the composer. Please check now and feel free to reopen this issue if error persistence.

**Comment by Daniel304** [comment]
thanks this works...
