### ISSUE TITLE
can't specify multiple product product ids by Rest api

### ISSUE THREAD

**Issue by ankit-sf** [mageprince/magento2-productAttachment#43]
http://i.prntscr.com/tfO06Mc2R62I-1Rf-rq6yw.png

**Comment by ankit-sf** [comment]
neither comma separated value works, nor array

**Comment by mageprince** [comment]
@ankit-sf Thank you for your report.
This issue has been solved. Please check commit: [d88ec88](https://github.com/mageprince/magento2-productAttachment/commit/d88ec8810e38f3b8cc631a7d3c2f7f17b62c3814)
