### ISSUE TITLE
Call to undefined method getAttachments() in .../UiComponent.php

### ISSUE THREAD

**Issue by poveu** [mageprince/magento2-productAttachment#44]
Hi,
I'm using the latest version. I can't access product edit page from backend. Error log contains:

> PHP Fatal error:  Method Magento\Ui\TemplateEngine\Xhtml\Result::__toString() must not throw an exception, caught Error: Call to undefined method Magento\Catalog\Api\Data\ProductExtension::getAttachments() in /home/balticad/www/sklep.balticad.eu/public_html/vendor/magento/module-ui/Component/Wrapper/UiComponent.php on line 0

**Comment by mageprince** [comment]
@poveu I am not able to reproduce this issue.
I think you used the develop branch. **Please use a master branch.**

**Comment by poveu** [comment]
@mageprince Hi, I have installed your module via composer, so I don't think I used the develop branch :)
I will try to see if anything changed after updating to Magento 2.2.7 or 2.3 and will keep you updated on this.

**Comment by Azaciux** [comment]
@poveu Just to confirm I had a similar problem, but deleting and regenerating the `generated` folder fixed this for me.

Can confirm, doesn't seem to be an issue with Magento 2.3.3
