### ISSUE TITLE
Suggestion: Mysql8 support.

### ISSUE THREAD

**Issue by jeroenschipper** [mageprince/magento2-productAttachment#45]
Hi!

I was trying your module in my local environment which is running on mysql 8, but saddenly the REGEXP in Block/Productattachment.php does not work on mysql8. 

https://github.com/mageprince/magento2-productAttachment/blob/3825b6bf2009d02ec60e4ddbcd692fa014c0bf33/Block/Attachment.php#L161 

In the mysql8 docs there is an explanation and solution (i think) for this problem.
(https://dev.mysql.com/doc/refman/8.0/en/regexp.html#operator_regexp)

> The Spencer library supports word-beginning and word-end boundary markers ([[:<:]] and [[:>:]] notation). ICU does not. For ICU, you can use \b to match word boundaries; double the backslash because MySQL interprets it as the escape character within strings. 

Could you make the module mysql8 ready?

**Comment by mageprince** [comment]
@jeroenschipper This issue has been solved please check commit: [c4717d](https://github.com/mageprince/magento2-productAttachment/commit/c4717d476f1dfdb2f7d078b41e07ba4b91d873cd)
