### ISSUE TITLE
Not showing in the backend

### ISSUE THREAD

**Issue by developeruserextension** [mageprince/magento2-productAttachment#46]
I have installed the extension but it is not showing in the backend

**Comment by mageprince** [comment]
@developeruserextension This module is tested with the latest version of the Magento(2.2.7 and 2.3) and it's working fine without any issue.
You can manage attachments and settings from **Admin->Catalog->Product Attachments**

![dashboard magento admin](https://user-images.githubusercontent.com/24751863/49437306-3db87080-f7e1-11e8-8b05-c8433ac51f3c.png)
