### ISSUE TITLE
Problem With $collection->getSelect()->where("products LIKE '%".$productId."%'");

### ISSUE THREAD

**Issue by julien30** [mageprince/magento2-productAttachment#5]
Hello,
I have a problem with /block/attacment.php on line 93 with operator like%%

The problem is in frontend.. If i have a product with one file on productID **127**, the attachement is also on productID 1**127**, **127**1, **127**2, **127**3, etc...

But if i replace LIKE%% by LIKE or = the problem is the possible 2nd file not appear

 Another problem : 

The file on product tab not appear. The paramters is Ok in Show "On Product Tab : YES".

(sorry for my english)
Thank's for your help

**Comment by mageprince** [comment]
@julien30 , Thanks for posting issue. I will get back after checking this issue.

**Comment by mageprince** [comment]
@julien30 ,
Please change code from

>  app/code/Prince/Productattach/Block/Attachment.php

 In function **getAttachment()**  `$collection->getSelect()->where("products LIKE '%".$productId."%'");` **to** `$collection->getSelect()->where("products REGEXP '[[:<:]]".$productId."[[:>:]]'");`

For Product Tab, it's working fine in default Magento store. Please make sure you flush the cache after changes of configuration settings.

Thank You.

**Comment by julien30** [comment]
Hi, @prince108 
Thank's for the correction ! 👍 it's perfect ! 
For Product Tab, it's not ok for me, my magento store is in 2.1.5 version.
I execute this command for flush the cache : php bin/magento cache:flush
but the tab not appear :( any solution ?
thank's

**Comment by mageprince** [comment]
Hi @julien30,

Product Tab is working fine in default Magento. But you use external module for product tab so you need to add a new ProductAttach tab. Add new tab with 
**Block:** `Prince\Productattach\Block\Attachment`
**Template:** `Prince_Productattach::attachment.phtml`

Thank You
Prince Patel

**Comment by julien30** [comment]
Hi @prince108 
It work perfectly ! 👍 
Thank's
