### ISSUE TITLE
404 admin error

### ISSUE THREAD

**Issue by RockMariska** [mageprince/magento2-productAttachment#51]
Hi,

I've installed the module manual in app/code/ 
made a new file called 'Prince" and moved the files into the "Prince" file.
followed by commands php bin/magento setup:upgrade, flushed alle caches.
finally the backend >catalog showed the add icons and add file
but when trying to open them it gives a 404 error on the admin area (backend)

what am i missing here?

**Comment by mageprince** [comment]
@RockMariska Please remove entry `Prince_Productattach` from `setup_module` table and run following commands:

php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
php bin/magento cache:flush

**Comment by RockMariska** [comment]
Hi Prince Patel,
 
Thank you very much for your reply, do you mean to remove it from database? 
 
As I look into the database table prince_productattach it is allready empty, shoudl i delete the whole table?
 
When I look into /app/code/Prince/magento2-productAttachment-master/Setup/
There is only a file InstallSchema.php
 
Sorry I’m a little lost now how to solve the issue, can you please explain?
 
Thank you very much for your help,
Kind regards,
Mariska 
 
 
Van: Prince Patel [mailto:notifications@github.com] 
Verzonden: woensdag 9 januari 2019 07:39
Aan: mageprince/magento2-productAttachment <magento2-productattachment@noreply.github.com>
CC: RockMariska <mariska@rockmart.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [mageprince/magento2-productAttachment] 404 admin error (#51)
 
@RockMariska Please remove entry Prince_Productattach from setup_module table and run following commands:
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
php bin/magento cache:flush

**Comment by mageprince** [comment]
@RockMariska Just open `setup_module` table from the database. And delete row `Prince_Productattach` and run commands as described above.

**Comment by RockMariska** [comment]
Thank yo uso much for your assistance!
I’ve done as you’ve mentioned, just in the backend I still have Magento Admin 404 Error when truing to open the Manage attachments or manage icons.
Then I’ve deleted all caches, then did the staic-content-deploy –f again, no changes, so I’ve updated the composer, flushed cache again.
While trying to php bin/magento setup:di:compile it gives me: 
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 32.0 MiBPHP Fatal error:  Interface 'Prince\Productattach\Api\Data\FileiconInterface' not found in /data/web/magento2_staging/app/code/Prince/magento2-productAttachment-master/Model/Fileicon.php on line 33
 
 
Van: Prince Patel [mailto:notifications@github.com] 
Verzonden: donderdag 10 januari 2019 07:01
Aan: mageprince/magento2-productAttachment <magento2-productattachment@noreply.github.com>
CC: RockMariska <mariska@rockmart.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [mageprince/magento2-productAttachment] 404 admin error (#51)
 
@RockMariska Just open setup_module table from the database. And delete row Prince_Productattach and run commands as described above.
