### ISSUE TITLE
not working on 2.2.6

### ISSUE THREAD

**Issue by Sumayah90** [mageprince/magento2-productAttachment#52]
Hi 

The extension not working on Magento Commerce 2.2.7 

I have install it manually and via composer 

its not shown in Backend 

Thanks

**Comment by UglyWillDuckling** [comment]
@Sumayah90 , the module is working fine for me. Did you check under the Catalog menu tab?

**Comment by lexiconnect** [comment]
@Sumayah90 have you checked the settings - there is a new setting to disable the menu in the backend (under Information Tab).  This caused me a headache a couple of weeks ago!

**Comment by mageprince** [comment]
@Sumayah90 Thank you for your report.
This module is tested with Magento 2.2.7 and Magento 2.3.0 and it's working fine without any issue. Please check [Readme](https://github.com/mageprince/magento2-productAttachment/blob/master/README.md) for more details
