### ISSUE TITLE
Not registered handle productattach_grid_index_data_source

### ISSUE THREAD

**Issue by mtjweb** [mageprince/magento2-productAttachment#56]
I'm working with Magento 2.2.7 and getting the following error in Catalog -> Manage Attachements
`Not registered handle productattach_grid_index_data_source`

In Catalog -> Manage Icons I'm getting the following error:
`Not registered handle productattach_fileicon_grid_data_source`

The rest is working perfect.

**Comment by mageprince** [comment]
@mtjweb Please run following commands and let me know if error keep persistence
`php bin/magento set:up`
`php bin/magento s:d:c`
`php bin/magento c:f `

**Comment by mtjweb** [comment]
Found the problem.

I installed through composer. I reinstalled by uploading the files and it is now solved.
