### ISSUE TITLE
Magento 2.3.1 - sort order attribute on product.info.details block

### ISSUE THREAD

**Issue by simonlandry0** [mageprince/magento2-productAttachment#59]
**Issue**
In a recent PR https://github.com/magento/magento2/pull/19007/files someone added a required attribute (sort_order) for child block of the "product.info.details" block in the catalog_product_view.xml. 

This works fine if product attachment is the only external plugin that adds a block to the product.info.details block, but if another plugin adds a tab without a sort order, they will override each other causing the product attach tab to disappear. 

This is very much an edge case, but I think it would be nice to add the sort_order to improve plugin compatibility.

**Fix**
Adding
`                        <argument name="sort_order" xsi:type="string">30</argument>`
After line 10 of view/frontend/layout/catalog_product_view.xml

**Comment by mageprince** [comment]
@simonlandry0 Thank you for your suggestion.
