### ISSUE TITLE
Is not the extension free anymore?

### ISSUE THREAD

**Issue by matheusgontijo** [mageprince/magento2-productAttachment#60]
The GitHub tags for this project states that it's `for free`.

However, the code is not here and it's linking to the Magento Marketplace, which charges $25.

If it's now a paid extension, that's okay. Just willing to know, since it's tagged as `for free`.

Thanks.

**Comment by amenk** [comment]
Wondering if there were any Open Source contributions before to the module. What happened to those?

**Comment by amenk** [comment]
@atolcd-contrib I saw you made quite some contributions to the extension - are you interesting in maintaining it? We also might code-maintain it.

**Comment by tonyisworking** [comment]
If you want a copy of the code. There are plenty of forks.
Seems to be have been licensed under GPLv3 or later at that time outlined in the composer.json files

**Comment by mageprince** [comment]
@matheusgontijo I have removed free tags :)
