### ISSUE TITLE
Feature Request: Possibility to Update Attachments on a Per Product level

### ISSUE THREAD

**Issue by amenk** [mageprince/magento2-productAttachment#61]
I am following up @gotgelf this note: https://github.com/mageprince/magento2-productAttachment/issues/40#issuecomment-532142087 & https://github.com/mageprince/magento2-productAttachment/issues/40#issuecomment-532164830

We need that feature and the question is how we want to proceed.

1) Can you implement this feature for us in the extension?
2) If it is not planned, would you accept a patch from us to the commercial extension and take care of future updates.
3) Should we make an own extension which extends your API ? (no recommended)

**Comment by amenk** [comment]
We figured out that the attributes are already there in the GET request as extension attributes, so the question would be how this can be updated within the product update.

**Comment by amenk** [comment]
@mageprince can you give a quick feedback, for example if option 2) is feasible?

**Comment by mageprince** [comment]
@amenk Currently this module does not provide this functionality. We will implement this functionality in the next version of this module.

**Comment by amenk** [comment]
@mageprince that sounds awesome. Is there any rough timeline for the next version?

**Comment by mageprince** [comment]
@amenk It will take 8 to 10 days to approve a new version on Magento Marketplace. I will release a new version in a short time.

**Comment by amenk** [comment]
We would be happy to test a pre release if you sent it to my email: a dot menk at imi
dot de

**Comment by amenk** [comment]
We have some comments:

* Attachments ids should be specified in extension_attributes node in API calls body (Create/Update product calls)
#### What is important for implementation (on Magento side):
* During update call, product should be re-assigned to new extension_attributes, old assignment should be deleted
* If extension_attributes node is empty, product should not be attached to any attachments

**Comment by mageprince** [comment]
@amenk Please provide your email address.

**Comment by amenk** [comment]
@mageprince a.menk@imi.de
