### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by GreyWolfSys** [mageprince/magento2-productAttachment#62]
When I try and install from Extension Manager, it hangs when trying to process.

If I install manually, i get Class Prince\Productattach\Api\ProductattachInterface does not exist and the web site has the following error:

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Prince_Productattach data: current version - none, required version - 1.2.1

**Comment by mageprince** [comment]
Hi @GreyWolfSys,
Please run command: `php bin/magento setup:upgrade` to solve above issue.

Here are the steps to install the extension manually.
1. Unzip downloaded extension zip.
2. Copy `Prince` directory to `app/code/` directory. Folder path looks like (app/code/Prince/Productattach)
3. Run following commands:
`php bin/magento setup:upgrade`
`php bin/magento setup:di:compile`
`php bin/magento setup:static-content:deploy`
`php bin/magento cache:flush`
