### ISSUE TITLE
Error when clicking manage icons of attachments in backend

### ISSUE THREAD

**Issue by nazzau** [mageprince/magento2-productAttachment#63]
When I click manage attachments or manage icons I get the error message below. I use Magento version 2.3.3

<img width="1680" alt="Schermafbeelding 2019-11-08 om 20 40 45" src="https://user-images.githubusercontent.com/26454973/68505806-702be280-0268-11ea-8b2e-40d9d38ee2fc.png">

Thanks

**Comment by mageprince** [comment]
@nazzau We are not facing any issue with Magento 2.3.3 also this module is passed QA from Magento Marketplace.

However, we have a solution to your issue. Please remove some line of code from productattach_fileicon_index.xml and productattach_grid_index.xml.

**1.** Please remove following code from file **(productattach_fileicon_index.xml)** at _app/code/Prince/Productattach/view/adminhtml/ui_component/productattach_fileicon_index.xml_

`<argument name="context" xsi:type="configurableObject">
    <argument name="class" xsi:type="string">Magento\Framework\View\Element\UiComponent\Context</argument>
    <argument name="namespace" xsi:type="string">productattach_fileicon_index</argument>
</argument>`

**2.** And remove following code from the file **(productattach_grid_index.xml)** at
_app/code/Prince/Productattach/view/adminhtml/ui_component/productattach_grid_index.xml_

`<argument name="context" xsi:type="configurableObject">
		<argument name="class" xsi:type="string">Magento\Framework\View\Element\UiComponent\Context</argument>
		<argument name="namespace" xsi:type="string">productattach_grid_index</argument>
	</argument>`

**3.** Now run the following commands:

php bin/magento set:up
php bin/magento s:d:c
php bin/magento s:s:d
