### ISSUE TITLE
Bug with product-attachment listing by product detail

### ISSUE THREAD

**Issue by iskanderokilov** [mageprince/magento2-productAttachment#66]
Hi, i want to add file via Catalog - Products - Product Attachment.
Here is a Problem, when i want to select a file of preview page: the page contains more time only 1 some file. (see screenshot) [https://ibb.co/S0tgg53](https://ibb.co/S0tgg53)

**Comment by mageprince** [comment]
Hi @iskanderokilov We can't able to reproduce this issue. Can you please provide us video of the issue.

**Comment by iskanderokilov** [comment]
Hi, [here is a youtube link](https://youtu.be/Jx_W2DI-u4M)

**Comment by mageprince** [comment]
Hi @iskanderokilov We are unable to reproduce this issue. Please make sure you use latest version of the module. Can you please check the demo: http://demo.mageprince.com/
