### ISSUE TITLE
Product attachment tab is not showing on product details page

### ISSUE THREAD

**Issue by Charanjet** [mageprince/magento2-productAttachment#67]
Hi Prince,
I installed your extension that is very helpful to manage attachments. It was working after installation but now I can check it is not showing the attachment tab on product details page.
Please can you share but problem it can be

**Comment by mageprince** [comment]
Hi @Charanjet 
Please check that you enabled Show On Product Tab from **Admin->Catalog->Configuration->Attachment Configuration For Product Page->Show On Product Tab**
