### ISSUE TITLE
Class Mageprince\Productattach\Api\ProductattachInterface does not exist

### ISSUE THREAD

**Issue by mtjweb** [mageprince/magento2-productAttachment#68]
I upgraded to version 2.0.3 and got the following error when running the command php bin/magento setup:upgrade.

Class Mageprince\Productattach\Api\ProductattachInterface does not exist

I'm using Magento 2.3.5-p1

**Comment by mageprince** [comment]
@mtjweb Please try after run `php bin/magento s:d:c` or please remove generated/code and var/cache, var/page_cache.

**Comment by mtjweb** [comment]
Tried it, but the error is still there.

**Comment by mageprince** [comment]
@mtjweb Which was the old version of the product attachment module?

**Comment by mtjweb** [comment]
I'm not sure which version exactly, but I know it was somewhere in the first version. So v1.?.?

**Comment by mageprince** [comment]
Are you using composer to update the module ?

**Comment by mtjweb** [comment]
No, downloaded it on marketplace.magento.com.

**Comment by mageprince** [comment]
What is the module path ? like app/code/ ?

**Comment by mtjweb** [comment]
I see it, the path changed. I corrected it. But when I open a product under Catalog => Products, I'm getting the following error:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbname.prince_productattach_relation' doesn't exist, query was: SELECT `main_table`.* FROM `prince_productattach_relation` AS `main_table` WHERE (`product_id` = '46') 

I checked the database and the table prince_productattach_relation is missing.

**Comment by mageprince** [comment]
Yes, module path must be `app/code/Mageprince/Productattach` 
For missing table, just remove module entry `Prince_Productattach` and `Mageprince_Productattach` from table `setup_module` and run following commands.

`php bin/magento set:up`
`php bin/magento s:d:c`
`php bin/magento s:s:d`

**Comment by mtjweb** [comment]
Thank you, that solved the problem.

**Comment by mageprince** [comment]
Happy to help you. Please give review and rating on the module. Thank you :)
