### ISSUE TITLE
Circular dependency after upgrade to 2.4.3-p1

### ISSUE THREAD

**Issue by lphilippo** [mageprince/magento2-productAttachment#69]
We have been using the plugin on 2.4.2 without any issues, but during an upgrade to 2.4.3-p1, we were hit with memory allocation issues. The error that we were able to track down was:

```
Circular dependency: Magento\\Customer\\Model\\Customer depends on Mageprince\\Productattach\\Helper\\Data and vice versa.
```

We have temporarily worked around this by replacing:

`use Magento\Customer\Model\Session as CustomerSession; `

with 

`use Magento\Customer\Model\Session\Proxy as CustomerSession;`

in `Mageprince\Productattach\Helper\Data`

Not sure if this is the prefered solution though, as circular dependency workarounds are not recommended, as the logical issue remains in place.

Custom changes that we did for the plugin in this specific installation, were limited to overwriting the template files, so we don't expect any side effects from those.

**Comment by mageprince** [comment]
Hi @lphilippo, thank you for your report. We are unable to reproduce this issue with Magento 2.4.3-p1. Please remove generated folder and re-run the compilation to regenerate classes.
`php bin/magento s:d:c`

Yes, Proxy is the best and preferred solution for circular dependency.
