### ISSUE TITLE
Product attachment doesn't appear on product page

### ISSUE THREAD

**Issue by minaeid90** [mageprince/magento2-productAttachment#7]
Hi 
I install the extension on Magento system version 2.1.3, it is installed successfully.Then I add a new attachment in admin page and select the product which will be appeared on but it doesn't show anything
I try to clean and flush cache but it didn't make anything.
Can you help me to solve this issue?

Thanks

**Comment by mageprince** [comment]
This extension checked in default Magento 2.1 to 2.1.9 and also in Magento 2.1. Please provide screenshots of new/edit attachment form, product select grid, and configuration settings from admin.

**Comment by minaeid90** [comment]
I attached screenshots of the issue.
Thanks
![01](https://user-images.githubusercontent.com/2496189/32847788-a3f8d614-ca33-11e7-926e-3365de4c4fc0.png)
![02](https://user-images.githubusercontent.com/2496189/32847790-a44e0576-ca33-11e7-962c-fbf970b87db3.png)
![03](https://user-images.githubusercontent.com/2496189/32847792-a48db676-ca33-11e7-8883-a90af4bd02a9.png)
![04](https://user-images.githubusercontent.com/2496189/32847793-a4c91cf2-ca33-11e7-9044-135858318e1c.png)
![05](https://user-images.githubusercontent.com/2496189/32847794-a508b556-ca33-11e7-995b-1717b1a2fc08.png)
![06](https://user-images.githubusercontent.com/2496189/32847796-a601c2ae-ca33-11e7-9d28-664868ca6a74.png)

**Comment by mageprince** [comment]
All settings are looking good. Please enable default Magento luma theme and check. Also please check if other modules conflict or not.
