### ISSUE TITLE
Backend Demo: Demo user does not have integration access, How can we test the API

### ISSUE THREAD

**Issue by navneetkumar-pim-webkul** [mageprince/magento2-productAttachment#70]
I am trying to check your API with your backend demo, but the demo user does not have integration access. so please let me know how I can test the API is working or not?

https://demo.mageprince.com/admin/

**Comment by mageprince** [comment]
Dear @navneetbhardwaj, Unfortunately, there is no any way to test API with the demo site. You can purchase and test API with the extension and you can take a refund if it's not working as per your requirement.

Check this document for API: [Mageprince Product Attachment User Guide](https://marketplace.magento.com/media/catalog/product/prince-module-productattachment-2-1-6-ce/user_guides.pdf)
