### ISSUE TITLE
MySQL Primary Keys are Not Defined

### ISSUE THREAD

**Issue by lbve** [mageprince/magento2-productAttachment#72]
Defining Primary Keys (PK) is a requirement for a good database and table design. Primary Keys (PK) provides a method to uniquely identify a single row in any table. Using the InnoDB engine, which is the Magento default, in tables where no PK is defined, the first unique non-null key is the Primary Key. 

If no PK is available, InnoDB creates a hidden primary key (6 bytes). The problem with such type of key is that there is no control over it and its value is global for all tables without Primary Keys. This can cause contention problems performing simultaneous writes on these tables. This can lead to performance issues as they all share that global hidden PK index increment.

### Preconditions

**Magento Version**: Magento EE (Should be applied also on CE)

**Environment**: Production 

**Third party modules**: None

### Steps to reproduce
1. Run installation
2. Check the primary keys of new sql tables

### Expected result
1. All tables should have a primary key

### Actual result
1. prince_productattach_relation does not have primary key

This issue can cause contention problems performing simultaneous writes on these tables. This can lead to performance issues from deadlocks

**Comment by mageprince** [comment]
Hi @lbve Thank you for reporting this issue. It has already been resolved in the latest version (2.2.11) of the module: https://commercemarketplace.adobe.com/mageprince-module-product-attachment.html#product.info.details.release_notes
